-- Zitting HQ — Phase 3 of the 2026-09 revamp: the family photo library.
-- Photos (full + thumb in a private bucket), albums, people tags, per-person
-- favorites, attachments to other things (recipes, events, goals, trips,
-- quotes), soft delete. Idempotent; run before deploying Phase 3.

CREATE TABLE IF NOT EXISTS photos (
  id            text PRIMARY KEY,                       -- uuid generated by the app
  storage_path  text NOT NULL,                          -- 'photos' bucket key for the full-size (≤2048px) JPEG
  thumb_path    text,                                   -- square ~400px thumbnail
  width         integer,
  height        integer,
  taken_at      timestamptz,                            -- from EXIF when present, else the file's date
  uploaded_by   text REFERENCES family_members(id) ON DELETE SET NULL,
  caption       text,
  visibility    text NOT NULL DEFAULT 'family',         -- family | private | custom (custom → shares rows, entity_type 'photo')
  deleted_at    timestamptz,                            -- soft delete; purged after 30 days
  created_at    timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_photos_taken ON photos (taken_at DESC);
CREATE INDEX IF NOT EXISTS idx_photos_uploader ON photos (uploaded_by);
CREATE INDEX IF NOT EXISTS idx_photos_live ON photos (deleted_at) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS albums (
  id              text PRIMARY KEY,
  name            text NOT NULL,
  description     text,
  cover_photo_id  text REFERENCES photos(id) ON DELETE SET NULL,
  created_by      text REFERENCES family_members(id) ON DELETE SET NULL,
  visibility      text NOT NULL DEFAULT 'family',
  created_at      timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS album_photos (
  album_id  text NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  photo_id  text NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
  sort      integer NOT NULL DEFAULT 0,
  added_at  timestamptz DEFAULT now(),
  PRIMARY KEY (album_id, photo_id)
);
CREATE INDEX IF NOT EXISTS idx_album_photos_photo ON album_photos (photo_id);

CREATE TABLE IF NOT EXISTS photo_people (
  photo_id   text NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
  member_id  text NOT NULL REFERENCES family_members(id) ON DELETE CASCADE,
  PRIMARY KEY (photo_id, member_id)
);
CREATE INDEX IF NOT EXISTS idx_photo_people_member ON photo_people (member_id);

CREATE TABLE IF NOT EXISTS photo_favorites (
  photo_id   text NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
  member_id  text NOT NULL REFERENCES family_members(id) ON DELETE CASCADE,
  PRIMARY KEY (photo_id, member_id)
);

-- A photo attached to something else: recipe | event | goal | trip | quote | night (a dinner date).
CREATE TABLE IF NOT EXISTS attachments (
  entity_type  text NOT NULL,
  entity_id    text NOT NULL,
  photo_id     text NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
  sort         integer NOT NULL DEFAULT 0,
  PRIMARY KEY (entity_type, entity_id, photo_id)
);

INSERT INTO storage.buckets (id, name, public) VALUES ('photos', 'photos', false) ON CONFLICT (id) DO NOTHING;

ALTER TABLE photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE album_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE photo_people ENABLE ROW LEVEL SECURITY;
ALTER TABLE photo_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE attachments ENABLE ROW LEVEL SECURITY;
