-- Zitting HQ — Phase 5 of the 2026-09 revamp: family & personal goals, chores.
-- Goals have four progress kinds (checkoff, count, streak, savings — the last
-- links to the finance module's savings_goals). Chores are a weekly schedule
-- per person with completions an adult can check. Idempotent; run before
-- deploying Phase 5.

CREATE TABLE IF NOT EXISTS goals (
  id               text PRIMARY KEY,                        -- uuid generated by the app
  title            text NOT NULL,
  description      text,
  kind             text NOT NULL DEFAULT 'family',          -- family | personal
  progress_kind    text NOT NULL DEFAULT 'checkoff',        -- checkoff | count | streak | savings
  target           numeric(14,2),                           -- count: number to reach · streak: days · savings: taken from the linked goal
  unit             text,                                    -- count: 'books', 'miles', 'nights'…
  savings_goal_id  text REFERENCES savings_goals(id) ON DELETE SET NULL,
  cover_photo_id   text REFERENCES photos(id) ON DELETE SET NULL,
  due_on           date,
  hue              integer,                                 -- optional family hue 1..6 for the ring
  created_by       text REFERENCES family_members(id) ON DELETE SET NULL,
  visibility       text NOT NULL DEFAULT 'family',          -- family | private | custom (shares.entity_type = 'goal')
  completed_at     timestamptz,
  completed_by     text REFERENCES family_members(id) ON DELETE SET NULL,
  archived_at      timestamptz,
  sort             integer NOT NULL DEFAULT 0,
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_goals_live ON goals (archived_at) WHERE archived_at IS NULL;

CREATE TABLE IF NOT EXISTS goal_participants (
  goal_id    text NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
  member_id  text NOT NULL REFERENCES family_members(id) ON DELETE CASCADE,
  PRIMARY KEY (goal_id, member_id)
);

CREATE TABLE IF NOT EXISTS goal_checkins (
  id          serial PRIMARY KEY,
  goal_id     text NOT NULL REFERENCES goals(id) ON DELETE CASCADE,
  member_id   text REFERENCES family_members(id) ON DELETE SET NULL,
  day         date NOT NULL,
  amount      numeric(14,2) NOT NULL DEFAULT 1,
  note        text,
  created_at  timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_goal_checkins_goal ON goal_checkins (goal_id, day DESC);

CREATE TABLE IF NOT EXISTS chores (
  id                  text PRIMARY KEY,
  title               text NOT NULL,
  icon                text,                                 -- Lucide name from the app's picker
  assignee_member_id  text REFERENCES family_members(id) ON DELETE SET NULL,  -- NULL = anyone
  days                text NOT NULL DEFAULT '0123456',      -- weekday digits it's due, Sunday = 0
  time_of_day         text NOT NULL DEFAULT 'any',          -- morning | afternoon | evening | any
  points              integer NOT NULL DEFAULT 1,
  needs_check         boolean NOT NULL DEFAULT false,       -- an adult confirms it was really done
  active              boolean NOT NULL DEFAULT true,
  created_by          text REFERENCES family_members(id) ON DELETE SET NULL,
  sort                integer NOT NULL DEFAULT 0,
  created_at          timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chore_completions (
  id          serial PRIMARY KEY,
  chore_id    text NOT NULL REFERENCES chores(id) ON DELETE CASCADE,
  member_id   text REFERENCES family_members(id) ON DELETE SET NULL,   -- who did it
  day         date NOT NULL,
  done_at     timestamptz DEFAULT now(),
  checked_by  text REFERENCES family_members(id) ON DELETE SET NULL,
  checked_at  timestamptz,
  UNIQUE (chore_id, day)
);
CREATE INDEX IF NOT EXISTS idx_chore_completions_day ON chore_completions (day DESC);

ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE goal_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE goal_checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE chores ENABLE ROW LEVEL SECURITY;
ALTER TABLE chore_completions ENABLE ROW LEVEL SECURITY;
