/**
 * Single icon language for family and finance: Lucide, 2px stroke, round joins.
 * Ported from the design system's components/core/Icon.jsx — the guide fetched
 * SVGs from a CDN at runtime; production uses lucide-react with the same names.
 * Explicit named imports keep the bundle tree-shaken (no namespace import).
 *
 * GENERATED from the guide's ICONS list (+ an `extra` group this app adds) —
 * add a glyph to ICONS below AND to the import/map, then use it. An unknown
 * name renders an empty box and warns in dev (the old system rendered nothing
 * silently).
 */
import * as React from "react";
import type { LucideIcon } from "lucide-react";
import {
  House as I_house,
  Wallet as I_wallet,
  Calendar as I_calendar,
  Utensils as I_utensils,
  ShoppingCart as I_shopping_cart,
  Camera as I_camera,
  Image as I_image,
  ChefHat as I_chef_hat,
  Stethoscope as I_stethoscope,
  Quote as I_quote,
  Target as I_target,
  SquareCheck as I_square_check,
  Settings as I_settings,
  Bell as I_bell,
  Sparkles as I_sparkles,
  LogOut as I_log_out,
  User as I_user,
  Users as I_users,
  Receipt as I_receipt,
  CreditCard as I_credit_card,
  Landmark as I_landmark,
  PiggyBank as I_piggy_bank,
  HandCoins as I_hand_coins,
  Banknote as I_banknote,
  Repeat as I_repeat,
  ArrowLeftRight as I_arrow_left_right,
  TrendingUp as I_trending_up,
  TrendingDown as I_trending_down,
  FileUp as I_file_up,
  Tag as I_tag,
  BadgeCheck as I_badge_check,
  SlidersHorizontal as I_sliders_horizontal,
  Plus as I_plus,
  Minus as I_minus,
  X as I_x,
  Check as I_check,
  Pencil as I_pencil,
  Trash2 as I_trash_2,
  Upload as I_upload,
  Download as I_download,
  Share as I_share,
  Heart as I_heart,
  RefreshCw as I_refresh_cw,
  Search as I_search,
  Filter as I_filter,
  Ellipsis as I_ellipsis,
  Copy as I_copy,
  ExternalLink as I_external_link,
  ZoomIn as I_zoom_in,
  RotateCcw as I_rotate_ccw,
  ArrowRight as I_arrow_right,
  ArrowUpRight as I_arrow_up_right,
  ArrowDownRight as I_arrow_down_right,
  ArrowUpDown as I_arrow_up_down,
  ChevronsUpDown as I_chevrons_up_down,
  ChevronLeft as I_chevron_left,
  ChevronRight as I_chevron_right,
  ChevronDown as I_chevron_down,
  ChevronUp as I_chevron_up,
  GripVertical as I_grip_vertical,
  List as I_list,
  LayoutGrid as I_layout_grid,
  CalendarDays as I_calendar_days,
  CircleAlert as I_circle_alert,
  TriangleAlert as I_triangle_alert,
  Info as I_info,
  CircleCheck as I_circle_check,
  Clock as I_clock,
  Lock as I_lock,
  Eye as I_eye,
  EyeOff as I_eye_off,
  LoaderCircle as I_loader_circle,
  PartyPopper as I_party_popper,
  Flag as I_flag,
  MapPin as I_map_pin,
  Car as I_car,
  Sun as I_sun,
  Moon as I_moon,
  BookOpen as I_book_open,
  Leaf as I_leaf,
  Dumbbell as I_dumbbell,
  Plane as I_plane,
  MessageCircle as I_message_circle,
  ImageOff as I_image_off,
  CameraOff as I_camera_off,
  Video as I_video,
  BellRing as I_bell_ring,
  PersonStanding as I_person_standing,
  Activity as I_activity,
  Volume2 as I_volume_2,
  Lightbulb as I_lightbulb,
  MoonStar as I_moon_star,
  Timer as I_timer,
  ChartPie as I_chart_pie,
  Link as I_link,
  DollarSign as I_dollar_sign,
  ArrowDown as I_arrow_down,
  ArrowUp as I_arrow_up,
  LayoutDashboard as I_layout_dashboard,
  ChevronsLeft as I_chevrons_left,
  ChevronsRight as I_chevrons_right,
  Paperclip as I_paperclip,
  NotebookPen as I_notebook_pen,
  UtensilsCrossed as I_utensils_crossed,
  ShoppingBasket as I_shopping_basket,
  Gift as I_gift,
  Baby as I_baby,
  School as I_school,
  Bed as I_bed,
  SunMedium as I_sun_medium,
  KeyRound as I_key_round,
  Mail as I_mail,
  Phone as I_phone,
  Send as I_send,
  LogIn as I_log_in,
  UserPlus as I_user_plus,
  ShieldCheck as I_shield_check,
  CalendarCheck as I_calendar_check,
  CalendarPlus as I_calendar_plus,
  ImagePlus as I_image_plus,
  Folder as I_folder,
  FileText as I_file_text,
  Printer as I_printer,
  QrCode as I_qr_code,
  ScanLine as I_scan_line,
  WandSparkles as I_wand_sparkles,
  Star as I_star,
  ThumbsUp as I_thumbs_up,
  Smile as I_smile,
  Bookmark as I_bookmark,
  ClipboardList as I_clipboard_list,
  ListChecks as I_list_checks,
  CircleDot as I_circle_dot,
  Circle as I_circle,
  Square as I_square,
  SquarePen as I_square_pen,
  Pin as I_pin,
  Map as I_map,
  Route as I_route,
  Luggage as I_luggage,
  Ticket as I_ticket,
  Hotel as I_hotel,
  Navigation as I_navigation,
  Wifi as I_wifi,
  Bluetooth as I_bluetooth,
  Battery as I_battery,
  Refrigerator as I_refrigerator,
  CookingPot as I_cooking_pot,
  Carrot as I_carrot,
  Apple as I_apple,
  Egg as I_egg,
  Milk as I_milk,
  Wheat as I_wheat,
  Fish as I_fish,
  Beef as I_beef,
  Salad as I_salad,
  Soup as I_soup,
  Sandwich as I_sandwich,
  Pizza as I_pizza,
  Cake as I_cake,
  Coffee as I_coffee,
  CupSoda as I_cup_soda,
  IceCreamCone as I_ice_cream_cone,
  Candy as I_candy,
  Popcorn as I_popcorn,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "house": I_house,
  "wallet": I_wallet,
  "calendar": I_calendar,
  "utensils": I_utensils,
  "shopping-cart": I_shopping_cart,
  "camera": I_camera,
  "image": I_image,
  "chef-hat": I_chef_hat,
  "stethoscope": I_stethoscope,
  "quote": I_quote,
  "target": I_target,
  "square-check": I_square_check,
  "settings": I_settings,
  "bell": I_bell,
  "sparkles": I_sparkles,
  "log-out": I_log_out,
  "user": I_user,
  "users": I_users,
  "receipt": I_receipt,
  "credit-card": I_credit_card,
  "landmark": I_landmark,
  "piggy-bank": I_piggy_bank,
  "hand-coins": I_hand_coins,
  "banknote": I_banknote,
  "repeat": I_repeat,
  "arrow-left-right": I_arrow_left_right,
  "trending-up": I_trending_up,
  "trending-down": I_trending_down,
  "file-up": I_file_up,
  "tag": I_tag,
  "badge-check": I_badge_check,
  "sliders-horizontal": I_sliders_horizontal,
  "plus": I_plus,
  "minus": I_minus,
  "x": I_x,
  "check": I_check,
  "pencil": I_pencil,
  "trash-2": I_trash_2,
  "upload": I_upload,
  "download": I_download,
  "share": I_share,
  "heart": I_heart,
  "refresh-cw": I_refresh_cw,
  "search": I_search,
  "filter": I_filter,
  "ellipsis": I_ellipsis,
  "copy": I_copy,
  "external-link": I_external_link,
  "zoom-in": I_zoom_in,
  "rotate-ccw": I_rotate_ccw,
  "arrow-right": I_arrow_right,
  "arrow-up-right": I_arrow_up_right,
  "arrow-down-right": I_arrow_down_right,
  "arrow-up-down": I_arrow_up_down,
  "chevrons-up-down": I_chevrons_up_down,
  "chevron-left": I_chevron_left,
  "chevron-right": I_chevron_right,
  "chevron-down": I_chevron_down,
  "chevron-up": I_chevron_up,
  "grip-vertical": I_grip_vertical,
  "list": I_list,
  "layout-grid": I_layout_grid,
  "calendar-days": I_calendar_days,
  "circle-alert": I_circle_alert,
  "triangle-alert": I_triangle_alert,
  "info": I_info,
  "circle-check": I_circle_check,
  "clock": I_clock,
  "lock": I_lock,
  "eye": I_eye,
  "eye-off": I_eye_off,
  "loader-circle": I_loader_circle,
  "party-popper": I_party_popper,
  "flag": I_flag,
  "map-pin": I_map_pin,
  "car": I_car,
  "sun": I_sun,
  "moon": I_moon,
  "book-open": I_book_open,
  "leaf": I_leaf,
  "dumbbell": I_dumbbell,
  "plane": I_plane,
  "message-circle": I_message_circle,
  "image-off": I_image_off,
  "camera-off": I_camera_off,
  "video": I_video,
  "bell-ring": I_bell_ring,
  "person-standing": I_person_standing,
  "activity": I_activity,
  "volume-2": I_volume_2,
  "lightbulb": I_lightbulb,
  "moon-star": I_moon_star,
  "timer": I_timer,
  "chart-pie": I_chart_pie,
  "link": I_link,
  "dollar-sign": I_dollar_sign,
  "arrow-down": I_arrow_down,
  "arrow-up": I_arrow_up,
  "layout-dashboard": I_layout_dashboard,
  "chevrons-left": I_chevrons_left,
  "chevrons-right": I_chevrons_right,
  "paperclip": I_paperclip,
  "notebook-pen": I_notebook_pen,
  "utensils-crossed": I_utensils_crossed,
  "shopping-basket": I_shopping_basket,
  "gift": I_gift,
  "baby": I_baby,
  "school": I_school,
  "bed": I_bed,
  "sun-medium": I_sun_medium,
  "key-round": I_key_round,
  "mail": I_mail,
  "phone": I_phone,
  "send": I_send,
  "log-in": I_log_in,
  "user-plus": I_user_plus,
  "shield-check": I_shield_check,
  "calendar-check": I_calendar_check,
  "calendar-plus": I_calendar_plus,
  "image-plus": I_image_plus,
  "folder": I_folder,
  "file-text": I_file_text,
  "printer": I_printer,
  "qr-code": I_qr_code,
  "scan-line": I_scan_line,
  "wand-sparkles": I_wand_sparkles,
  "star": I_star,
  "thumbs-up": I_thumbs_up,
  "smile": I_smile,
  "bookmark": I_bookmark,
  "clipboard-list": I_clipboard_list,
  "list-checks": I_list_checks,
  "circle-dot": I_circle_dot,
  "circle": I_circle,
  "square": I_square,
  "square-pen": I_square_pen,
  "pin": I_pin,
  "map": I_map,
  "route": I_route,
  "luggage": I_luggage,
  "ticket": I_ticket,
  "hotel": I_hotel,
  "navigation": I_navigation,
  "wifi": I_wifi,
  "bluetooth": I_bluetooth,
  "battery": I_battery,
  "refrigerator": I_refrigerator,
  "cooking-pot": I_cooking_pot,
  "carrot": I_carrot,
  "apple": I_apple,
  "egg": I_egg,
  "milk": I_milk,
  "wheat": I_wheat,
  "fish": I_fish,
  "beef": I_beef,
  "salad": I_salad,
  "soup": I_soup,
  "sandwich": I_sandwich,
  "pizza": I_pizza,
  "cake": I_cake,
  "coffee": I_coffee,
  "cup-soda": I_cup_soda,
  "ice-cream-cone": I_ice_cream_cone,
  "candy": I_candy,
  "popcorn": I_popcorn,
};

/** Every glyph the product uses, by Lucide name, grouped as in the guide. */
export const ICONS: Record<string, string[]> = {
  modules: ["house", "wallet", "calendar", "utensils", "shopping-cart", "camera", "image", "chef-hat", "stethoscope", "quote", "target", "square-check", "settings", "bell", "sparkles", "log-out", "user", "users"],
  finance: ["receipt", "credit-card", "landmark", "piggy-bank", "hand-coins", "banknote", "repeat", "arrow-left-right", "trending-up", "trending-down", "file-up", "tag", "badge-check", "sliders-horizontal"],
  actions: ["plus", "minus", "x", "check", "pencil", "trash-2", "upload", "download", "share", "heart", "refresh-cw", "search", "filter", "ellipsis", "copy", "external-link", "zoom-in", "rotate-ccw", "arrow-right", "arrow-up-right", "arrow-down-right", "arrow-up-down", "chevrons-up-down", "chevron-left", "chevron-right", "chevron-down", "chevron-up", "grip-vertical", "list", "layout-grid", "calendar-days"],
  status: ["circle-alert", "triangle-alert", "info", "circle-check", "clock", "lock", "eye", "eye-off", "loader-circle", "party-popper", "flag"],
  life: ["map-pin", "car", "sun", "moon", "book-open", "leaf", "dumbbell", "plane", "message-circle", "image-off", "camera-off"],
  cameras: ["video", "bell-ring", "person-standing", "activity", "volume-2", "lightbulb", "moon-star", "timer"],
  extra: ["chart-pie", "link", "dollar-sign", "arrow-down", "arrow-up", "layout-dashboard", "chevrons-left", "chevrons-right", "paperclip", "notebook-pen", "utensils-crossed", "shopping-basket", "gift", "baby", "school", "bed", "sun-medium", "key-round", "mail", "phone", "send", "log-in", "user-plus", "shield-check", "calendar-check", "calendar-plus", "image-plus", "folder", "file-text", "printer", "qr-code", "scan-line", "wand-sparkles", "star", "thumbs-up", "smile", "bookmark", "clipboard-list", "list-checks", "circle-dot", "circle", "square", "square-pen", "pin", "map", "route", "luggage", "ticket", "hotel", "navigation", "wifi", "bluetooth", "battery", "refrigerator", "cooking-pot", "carrot", "apple", "egg", "milk", "wheat", "fish", "beef", "salad", "soup", "sandwich", "pizza", "cake", "coffee", "cup-soda", "ice-cream-cone", "candy", "popcorn"],
};

export type IconName = keyof typeof MAP | (string & {});

export interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  label?: string;
  className?: string;
  style?: React.CSSProperties;
}

export function Icon({ name, size = 20, color = "currentColor", label, className, style }: IconProps) {
  const Cmp = MAP[name as string];
  const base: React.CSSProperties = { display: "inline-block", flex: "none", verticalAlign: "middle", ...style };
  if (!Cmp) {
    if (process.env.NODE_ENV !== "production") console.warn(`[zh-ui] unknown icon "${String(name)}"`);
    return <svg aria-hidden width={size} height={size} viewBox="0 0 24 24" className={className} style={base} />;
  }
  return (
    <Cmp
      size={size}
      color={color}
      strokeWidth={2}
      role={label ? "img" : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
      className={className}
      style={base}
    />
  );
}

export const hasIcon = (name: string): boolean => name in MAP;
